// Generated by dts-bundle-generator v9.5.1

import { JwtVariables } from 'hono/jwt';

export type JWTContent = {
	sub: string;
	name: string;
	picture: string;
	givenName: string;
	familyName: string;
	exp: number;
};
export type Variables = JwtVariables<JWTContent>;
declare const app: import("hono/hono-base").HonoBase<{
	Variables: Variables;
}, {
	"/api/private/*": {};
} & {
	"/api/private/user": {
		$get: {
			input: {};
			output: {
				isAdmin: boolean;
				sub: string;
				name: string;
				picture: string;
				givenName: string;
				familyName: string;
				exp: number;
			};
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/api/private/links": {
		$get: {
			input: {};
			output: {
				links: {
					id: number;
					title: string;
					description: string;
					url: string;
					iconUrl: string;
				}[];
				id: number;
				createdAt: string;
				updatedAt: string;
				name: string;
				lexorank: string;
			}[];
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/api/public/links": {
		$get: {
			input: {};
			output: {
				links: {
					id: number;
					title: string;
					description: string;
					url: string;
					iconUrl: string;
				}[];
				id: number;
				createdAt: string;
				updatedAt: string;
				name: string;
				lexorank: string;
			}[];
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/auth": {
		$post: {
			input: {
				json: {
					idToken: string;
				};
			};
			output: {
				error: string;
			};
			outputFormat: "json";
			status: 400;
		} | {
			input: {
				json: {
					idToken: string;
				};
			};
			output: {
				success: boolean;
			};
			outputFormat: "json";
			status: import("hono/utils/http-status").ContentfulStatusCode;
		};
	};
} & {
	"/": {
		$get: {
			input: {};
			output: undefined;
			outputFormat: "redirect";
			status: 302;
		};
	};
}, "/">;
export type AppType = typeof app;

export {};
